name: Generate Pac-Man Contributions

on:
  # Runs every 12 hours
  schedule:
    - cron: "0 */1 * * *" 

  # Allows manual trigger from GitHub Actions UI
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to output branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch and switch to output branch
        run: |
          git fetch origin output
          git checkout output || git checkout -b output

      - name: Generate Pac-Man
        uses: AndreRuperto/svg-pacman-contributions@main
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token:     ${{ secrets.GITHUB_TOKEN }}
          theme:            github-dark
          output_directory: dist

      - name: Copy to generic file name
        run: pacman-contribution-graph-dark.svg github-contribution-grid-pacman.svg

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Pac-Man animation" || echo "Nothing to commit"
          git push origin output
